name: backend
version: 0.1.0.0
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2022 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/backend#readme>

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - bytestring
  - text
  - unordered-containers
  - containers
  - stm
  - wai
  - wai-logger
  - warp
  - servant
  - servant-server
  - websockets
  - wai-websockets
  - servant-websockets
  - wai-app-static
  - hashable
  - deriving-aeson

library:
  source-dirs: src

executables:
  backend-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - backend

# tests:
#   backend-test: 
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - base
#       - backend
#       - hspec
#       - hspec-wai
#       - hspec-wai-json
#       - aeson
