edition                     = "2021"
hard_tabs                   = false
force_explicit_abi          = true
max_width                   = 100
merge_derives               = true
newline_style               = "Auto"
remove_nested_parens        = true
reorder_imports             = true
reorder_modules             = true
tab_spaces                  = 4
use_field_init_shorthand    = true
use_small_heuristics        = "Default"
use_try_shorthand           = false
format_code_in_doc_comments = true
imports_granularity         = "Crate"