name:                simplex-cheat
version:             0.1.0.0
github:              "value/simplex-cheat"
license:             BSD3
author:              "value"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/value/simplex-cheat#readme>

default-extensions:
- DuplicateRecordFields

dependencies:
- base >= 4.7 && < 5
- aeson
- async
- bytestring
- directory
- exceptions
- filepath
- focus
- hashable
- http-client
- mtl
- random
- random-shuffle
- servant
- servant-client
- servant-docs
- servant-server
- stm
- stm-containers
- string-interpolate
- text
- time
- transformers
- unordered-containers
- wai
- warp
- yaml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  simplex-cheat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simplex-cheat

tests:
  simplex-cheat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simplex-cheat
