name:                repohs
version:             0.1.0.0
github:              "githubuser/repohs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/repohs#readme>

dependencies:
- base >= 4.7 && < 5
- wreq
- lens
- bytestring
- directory
- uri
- filepath
- async
- fmt
- MissingH
- zip
- conduit-extra
- containers
- process
- aeson
- scientific

library:
  source-dirs: src

executables:
  repohs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repohs

tests:
  repohs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - repohs
