name: optics-by-example
version: 0.1.0.0
github: "value/optics-by-example"
license: BSD3
author: "value"
maintainer: "value"
copyright: "value"

# extra-source-files:
#   - README.md 
#   - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/value/optics-by-example#readme>

default-extensions:
  - ImportQualifiedPost
  - OverloadedRecordDot

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  dependencies:
    - aeson
    - containers
    - lens
    - lens-aeson
    - mtl
    - text
    - template-haskell
    - bytestring
    - either
    - generic-lens
    - split

tests:
  docs:
    main: test/Main.hs
    dependencies:
      - text
      - lima
      - string-interpolate
