name: developers-roadmap
license: BSD3
version: 0.0.1

dependencies:
  - aeson
  - async
  - base >= 4.7 && < 5
  - binary <= 0.8.9.1
  - breakpoint
  - bytestring
  - containers
  - deepseq
  - effectful
  - exceptions
  - first-class-families
  - fused-effects
  - fused-effects-exceptions
  - generic-lens
  - http-client
  - http-client-tls
  - http-types
  - large-anon
  - large-generics  
  - lens
  - lifted-base
  - managed
  - matrix
  - monad-control
  - monad-logger
  - mtl
  - random
  - string-interpolate
  - template-haskell
  - text
  - time
  - transformers
  - transformers-base
  - unliftio
  - unordered-containers

executables:
  README:
    main: README.hs

ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-safe-haskell-mode
  - -Wno-unsafe
  - -Wno-missing-imports

library:
  source-dirs:
    - src
