name: nix-managed
version: 0.1.0.0
github: "value/nix-managed"
license: BSD3
author: "value"
maintainer: "value"
copyright: "value"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/value/nix-managed#readme>

default-extensions:
  - ImportQualifiedPost

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - lens
    - generic-lens
    - time
    - string-interpolate
    - data-default
    - tasty-hunit
    - tasty
    - text
    - hedgehog
    - tasty-hedgehog
    - breakpoint

executables:
  nix-managed:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nix-managed

# tests:
#   conversions:
#     main: Main.hs
#     source-dirs: test
#     dependencies:
#       - nix-managed
#       - lima
#       - directory
#       - pretty-simple