- heading: "Developers' Roadmap"
  subDirs:
    - hsPrefix: "developers-roadmap"
      mdPrefix: "developers-roadmap"
      maxDepth: 1
    - hsPrefix: "developers-roadmap/src/Try"
      mdPrefix: "developers-roadmap"
      maxDepth: 3
- heading: "Optics By Example"
  subDirs:
    - hsPrefix: "optics-by-example/src"
      mdPrefix: "optics-by-example"
      maxDepth: 1
- heading: "Thinking with Types"
  subDirs:
    - hsPrefix: "thinking-with-types/src"
      mdPrefix: "thinking-with-types"
      maxDepth: 1
- heading: "Sockets and Pipes"
  subDirs:
    - hsPrefix: "sockets-and-pipes-notes/src"
      mdPrefix: "sockets-and-pipes-notes"
      maxDepth: 1