- heading: "Developers' Roadmap"
  subDirs:
    - hsPrefix: "developers-roadmap/src/Try"
      mdPrefix: "developers-roadmap"
      hsModules:
        - "Aeson/HKD"
        - "Debug/Breakpoint"
        - "Effectful/Dynamic"
        - "Exceptions/Exceptions"
        - "Exceptions/Theory"
        - "Functions/Composition"
        - "Functions/Folds"
        - "Functions/General"
        - "FusedEffects/ReinterpretingEffects"
        - "FusedEffects/UndoIO"
        - "GADT/GADT"
        - "Generics/Generics"
        - "ImplicitParams/ImplicitParams"
        - "IO/RandomNumbers"
        - "Lens/MissingKey"
        - "Lens/Node"
        - "Misc/Determinant"
        - "Monads/FunctionalDependencies"
        - "Monads/MonadBaseControl"
        - "Monads/Monads"
        - "ParallelAndConcurrentHaskell/Exceptions"
        - "ParallelAndConcurrentHaskell/MVar"
        - "ParallelAndConcurrentHaskell/STM"
        - "TemplateHaskell/ConstructorTags/Declare"
        - "TemplateHaskell/ConstructorTags/Use"
        - "TemplateHaskell/Typed/Declare"
        - "TemplateHaskell/Typed/Use"
        - "Test/Theory"
        - "TypeClasses/Monoid"
        - "TypeClasses/Theory"
        - "TypeClasses/TypeClasses"
        - "TypeFamilies/Theory"
        - "TypeFamilies/TypeFamilies"
    - hsPrefix: "developers-roadmap"
      mdPrefix: "developers-roadmap"
      hsModules:
        - "README"
- heading: "Optics By Example"
  subDirs:
    - hsPrefix: "optics-by-example/src"
      mdPrefix: "optics-by-example"
      hsModules:
        - "Extra"
        - "Book"
