- heading: "Developers' Roadmap"
  subDirs:
    - hsPrefix: "developers-roadmap"
      mdPrefix: "developers-roadmap"
      maxDepth: 1
    - hsPrefix: "developers-roadmap/src/Try"
      mdPrefix: "developers-roadmap"
      maxDepth: 3
- heading: "Optics By Example"
  subDirs:
    - hsPrefix: "optics-by-example/src"
      mdPrefix: "optics-by-example"
      maxDepth: 1
