default-extensions:
- TypeApplications
- ImportQualifiedPost
- BlockArguments
- QuasiQuotes
- NoOverloadedStrings
- InstanceSigs

dependencies:
- base >= 4.7 && < 5
- breakpoint

executables:
  TryBreakpoint:
    main: app/TryBreakpoint.hs

library:
  source-dirs:
    - src

license: BSD3

name: developers-roadmap

version: 0.1.0.0
