default-extensions:
  - TypeApplications
  - ImportQualifiedPost
  - BlockArguments
  - QuasiQuotes
  - NoOverloadedStrings
  - InstanceSigs

dependencies:
  - base >= 4.7 && < 5
  - breakpoint
  - random
  - unordered-containers
  - bytestring
  - binary <= 0.8.9.1
  - async
  - rio
  - transformers
  - deepseq
  - aeson
  - http-client-tls
  - http-client
  - time
  - bytestring
  - http-types
  - managed
  - mtl
  - exceptions
  - lifted-base
  - monad-control
  - effectful
  - fused-effects
  - fused-effects-exceptions
  - containers

executables:
  Breakpoint:
    main: app/Breakpoint.hs
  RandomNumbers:
    main: app/RandomNumbers.hs

library:
  source-dirs:
    - src

license: BSD3

name: nix-managed

version: 0.1.0.0
