default-extensions:
  - TypeApplications
  - ImportQualifiedPost
  - BlockArguments
  - QuasiQuotes
  - NoOverloadedStrings
  - InstanceSigs

dependencies:
  - base >= 4.7 && < 5
  - breakpoint
  - random
  - unordered-containers
  - bytestring
  - binary <= 0.8.9.1

executables:
  TryBreakpoint:
    main: app/TryBreakpoint.hs
  RandomNumbers:
    main: app/RandomNumbers.hs

library:
  source-dirs:
    - src

license: BSD3

name: nix-managed

version: 0.1.0.0
