default-extensions:
  - AllowAmbiguousTypes
  - BlockArguments
  - DataKinds
  - FlexibleContexts
  - FlexibleInstances
  - ImportQualifiedPost
  - InstanceSigs
  - MultiParamTypeClasses
  - NoOverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - TypeApplications
  - TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - async
  - binary <= 0.8.9.1
  - breakpoint
  - bytestring
  - bytestring
  - containers
  - deepseq
  - effectful
  - exceptions
  - fused-effects
  - fused-effects-exceptions
  - http-client
  - http-client-tls
  - http-types
  - lifted-base
  - managed
  - monad-control
  - mtl
  - random
  - rio
  - time
  - transformers
  - template-haskell
  - unordered-containers

executables:
  Breakpoint:
    main: app/Breakpoint.hs
  RandomNumbers:
    main: app/RandomNumbers.hs
  README:
    main: README.hs

library:
  source-dirs:
    - src

tests:
  docs:
    main: test/Docs.hs
    dependencies:
      - turtle
      - string-interpolate
      - text
      - lima
      - data-default

license: BSD3

name: nix-managed

version: 0.1.0.0
