name:                try-esqueleto
version:             0.1.0.0
github:              "value/try-esqueleto"
license:             BSD3
author:              "value"
maintainer:          "value"
copyright:           "value"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            value

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/value/try-esqueleto#readme>

default-extensions:
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- TemplateHaskell
- QuasiQuotes
- AllowAmbiguousTypes
- BlockArguments
- DataKinds
- DeriveGeneric
- DerivingStrategies
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- MultiParamTypeClasses
- OverloadedRecordDot
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- UndecidableInstances

dependencies:
- base >= 4.7 && < 5
- esqueleto
- persistent
- text
- mtl
- transformers
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- with-utf8
- pretty-simple
- string-interpolate
- aeson
- yaml
- resourcet

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  try-esqueleto:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-esqueleto

tests:
  try-esqueleto-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - try-esqueleto
