apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  type: NodePort # Sets service type
  ports:
    - port: 5432 # Sets port to run the service
      name: service-port
      targetPort: server-port
      nodePort: 30002
  selector:
    app: postgres
