apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-data-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: rabbitmq-gui-port
      protocol: TCP
      port: 15672
      targetPort: 15672