default-extensions:
- TypeApplications

dependencies:
- base >= 4.7 && < 5

executables:
  A:
    main: Main.hs
    source-dirs: ./Modules/A
  B:
    dependencies:
    - filepath
    - directory
    - relude
    main: Main.hs
    source-dirs: ./Modules/B

ghc-options:
- -Wall

license: BSD3

name: nix-managed

version: 0.1.0.0
