jobs:
  _1_update_flake_locks:
    name: Nix CI
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
            keep-outputs = true
            keep-derivations = true
          install_url: https://releases.nixos.org/nix/nix-2.16.1/install
      - name: Restore and cache Nix store
        uses: deemp/cache-nix-too@v1
        with:
          key: nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
          restore-keys: |
            nix-${{ matrix.os }}-cachix-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
            nix-${{ matrix.os }}-cachix-
      - if: matrix.os == 'ubuntu-22.04'
        name: Config git for github-actions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - if: matrix.os == 'ubuntu-22.04'
        name: Format Nix files
        run: |+
          nix run .#format

      - if: matrix.os == 'ubuntu-22.04'
        name: Update flake locks
        run: |+
          git pull --rebase --autostash

          nix run .#updateLocks

          git commit -a -m "action: Update flake locks" \
                                 && git push || echo "push failed!"

      - env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          CACHIX_CACHE: ${{ secrets.CACHIX_CACHE }}
        name: Push flakes to Cachix
        run: |+
          nix run .#pushToCachix

    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
          - ubuntu-20.04
          - ubuntu-22.04
  _2_front:
    name: Publish static files
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            substituters = https://cache.nixos.org/ https://nix-community.cachix.org https://cache.iog.io https://deemp.cachix.org
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= deemp.cachix.org-1:9shDxyR2ANqEPQEEYDL/xIOnoPwxHot21L5fiZnFL18=
            keep-outputs = true
            keep-derivations = true
          install_url: https://releases.nixos.org/nix/nix-2.16.1/install
      - name: Restore and cache Nix store
        uses: deemp/cache-nix-too@v1
        with:
          key: nix-${{ runner.os }}-static-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
          restore-keys: |
            nix-${{ runner.os }}-static-${{ hashfiles('**/flake.nix', '**/flake.lock') }}
            nix-${{ runner.os }}-static-
      - name: Build docs
        run: |+
          nix run .#genDocs

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
name: Nix CI
"on":
  pull_request: {}
  push: {}
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}
